export default {
    banks: {
        chase: {
            bankName: 'Chase Bank',
            addressLine1: '270 Park Ave',
            city: 'New York',
            zipcode: '10017',
            state: 'New York',
            ABA: '021000021',
        },
        boa: {
            bankName: 'Bank of America',
            addressLine1: '100 N Tryon St',
            city: 'Charlotte',
            zipcode: '28255',
            state: 'North Carolina',
            ABA: '053000196',
        },
        citi: {
            bankName: 'Citibank',
            addressLine1: '399 Park Ave',
            city: 'New York',
            zipcode: '10022',
            state: 'New York',
            ABA: '021000089',
        }
    },
    states: [
        'Alaska',
        'Alabama',
        'Arkansas',
        'American Samoa',
        'Arizona',
        'California',
        'Colorado',
        'Connecticut',
        'District ',
        'of Columbia',
        'Delaware',
        'Florida',
        'Georgia',
        'Guam',
        'Hawaii',
        'Iowa',
        'Idaho',
        'Illinois',
        'Indiana',
        'Kansas',
        'Kentucky',
        'Louisiana',
        'Massachusetts',
        'Maryland',
        'Maine',
        'Michigan',
        'Minnesota',
        'Missouri',
        'Mississippi',
        'Montana',
        'North Carolina',
        'North Dakota',
        'Nebraska',
        'New Hampshire',
        'New Jersey',
        'New Mexico',
        'Nevada',
        'New York',
        'Ohio',
        'Oklahoma',
        'Oregon',
        'Pennsylvania',
        'Puerto Rico',
        'Rhode Island',
        'South Carolina',
        'South Dakota',
        'Tennessee',
        'Texas',
        'Utah',
        'Virginia',
        'Virgin Islands',
        'Vermont',
        'Washington',
        'Wisconsin',
    ]
};